name: DockerImageDjango

on:
  push:
    branches: [ devops ]
env: 
  LOGIN : 'sewer01'
  #PSWD  : ${{ secrets.PSWD }}
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag sewer01/django:devops
  
    - name: deploy
      run: |
        docker login -u ${{ env.LOGIN }} -p ${{ secrets.PSWD }}
        docker push sewer01/django:devops
    

