name: DockerImageDjango

on:
  push:
    branches: [ devops ]
env: 
  LOGIN : 'sewer01'
  #PSWD  : ${{ secrets.PSWD }}
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag sewer01/django
  
    - name: runing
      run: docker run -p 80:80 sewer01/django

